function [scenario, egoVehicle] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.9 (R2020b) and Automated Driving Toolbox 3.2 (R2020b).
% Generated on: 25-Apr-2021 13:15:58

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-0.5 0.8 0;
    39.6 0.5 0;
    80.5 -0.2 0;
    102.1 -0.2 0;
    119.3 -8.7 0;
    125 -31.3 0;
    125 -59.9 0;
    125 -90.1 0;
    125 -149.2 0;
    125 -175.8 0];
road(scenario, roadCenters, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-0.5 0.9 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [-0.5 0.9 0;
    8 0.7 0;
    19.5 1.1 0;
    31.4 1.1 0;
    47.4 0.3 0;
    61 -0.5 0;
    71.1 -0.9 0;
    79.9 -0.3 0;
    90.9 0.1 0;
    102 -0.2 0;
    111.8 -2.5 0;
    119.4 -7.4 0;
    123.6 -16.9 0;
    125.1 -29.9 0;
    125.1 -45.5 0;
    125.1 -60.2 0;
    125.1 -90.3 0;
    125.2 -149.3 0;
    124.8 -175.2 0];
speed = [15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15];
trajectory(egoVehicle, waypoints, speed);

